version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - run: 
        name: Install dependicies
        command: | 
          npm install
      - run: 
        name: Run tests
        command: |
          npm test
      - run: 
        name: Build project
        command: |
          npm run build
      - run:
        name: Build image
        command: |
          docker build -t ppv2 .
      
workflows:
  pure-paradise-server:
    jobs:
      - deploy

    