version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    executor: heroku/default
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - run: npm install
      - run: npm test
      - run: npm run build
      - when:
        condition:
          - equal: [ master, << pipeline.git.branch >> ]
        steps:
          - heroku/push-docker-image:
      
workflows:
  pure-paradise-server:
    jobs:
      - deploy
    