version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - restore_cache: 
        key: v1-dependencies-{{ checksum "./package.json" }}
      - run: npm install
      - save_cache: 
        paths:
            - ./node_modules
            - ./.npm
            - ./.cache
      - run: npm test
      - run: npm run build
      
workflows:
  pure-paradise-server:
    jobs:
      - deploy

    