version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npm run build
      
workflows:
  pure-paradise-server:
    jobs:
      - deploy

    