version: 2.1

orbs:
  heroku: circleci/heroku@1.2.3

jobs:
  deploy:
    parameters:
      process-types: web
    executor: heroku/default
    docker: 
      - image: circleci/node:14.8.0
    steps:
      - checkout
      - heroku/install
      - setup_remote_docker
      - run: npm install
      - run: npm test
      - run: npm run build
      - push-docker-image:
        process-types: web
      
workflows:
  pure-paradise-server:
    jobs:
      - deploy
    